runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://admin:admin@ds025409.mlab.com:25409/heroku_x4qz32mn
  APP_ID: <your-app-id>
  MASTER_KEY: <your-master-key>
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  